---
- name: Deploy Polymetrie Application
  hosts: localhost
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Install Helm Chart for PostgreSQL
      kubernetes.core.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        create_namespace: true
        values:
          postgresqlPassword: "cBxkAqQtZR"

    - name: Install Helm Chart for Redis
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: default
        #create_namespace: true

    - name: Wait for Redis and Postgres deployment to finish
      pause:
        seconds: 25

    # - name: Extract Redis password from Kubernetes secret
    #   shell: kubectl get secret --namespace default redis -o jsonpath="{.data.redis-password}" | base64 -d
    #   register: redis_password_result
    #   changed_when: false

    # - name: Debug - Display Redis password result
    #   debug:
    #     var: redis_password_result

    # - name: Set REDIS_PASSWORD environment variable
    #   ansible.builtin.set_fact:
    #     redis_password: "{{ redis_password_result.stdout }}"



    - name: Apply Kubernetes YAML files
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) }}"
      with_items:
        - polymetrie-deployment.yaml
        - polymetrie-service.yaml
        - polymetrie-ingress.yaml
