- name: Deploy Polymetrie Application
  hosts: localhost
  gather_facts: false
  become: yes

  tasks:
    - name: Install Helm Chart for Redis
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: default
        create_namespace: true
        values:
          redisPassword: "ov6D2EYYcb"

    - name: Install Helm Chart for PostgreSQL
      kubernetes.core.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        create_namespace: true
        values:
          postgresqlPassword: "cBxkAqQtZR"

    - name: Apply Kubernetes YAML files
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) }}"
      with_items:
        - polymetrie-deployment.yaml
        - polymetrie-service.yaml
        - polymetrie-ingress.yaml
