apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polymetrie-app-monitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: polymetrie-app
  endpoints:
  - port: "5000"
