apiVersion: v1
data:
  server.insecure: "true"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"server.insecure":"true"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-01-12T14:13:05Z","labels":{"app.kubernetes.io/name":"argocd-cmd-params-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-cmd-params-cm","namespace":"argocd","resourceVersion":"1859969758","uid":"db061df1-d3e2-4c3b-bdc3-378f34ba57f0"}}
  creationTimestamp: "2024-01-12T14:13:05Z"
  labels:
    app.kubernetes.io/name: argocd-cmd-params-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cmd-params-cm
  namespace: argocd
  resourceVersion: "1923970287"
  uid: db061df1-d3e2-4c3b-bdc3-378f34ba57f0
