apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.6.2
  count: 1
  config:
    monitoring.ui.ccs.enabled: false
  elasticsearchRef:
    name: elastic-cluster
  podTemplate:
    spec:
      priorityClassName: elastic-cluster-high-priority
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          - name: SERVER_PUBLICBASEURL
            value: "http://kibana.orch-team-a.pns-projects.fr.eu.org"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.4
          limits:
            memory: 2.5Gi
            cpu: 2