apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polymetrie-app-monitor
  namespace: prometheus
  labels:
    name: polymetrie-app-monitor
spec:
  selector:
    matchLabels:
      app: polymetrie-app
  namespaceSelector:
    matchNames:
    - "default"
  endpoints:
    - port: polymetrie-port
      interval: 15s
