apiVersion: apps/v1
kind: Deployment
metadata:
  name: polymetrie-app
  labels:
    app: polymetrie-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: polymetrie-app
  template:
    metadata:
      labels:
        app: polymetrie-app
    spec:
      containers:
      - name: polymetrie-app
        image: leolebossducloud/polymetrie:latest
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_DB
          value: "0"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis
              key: redis-password
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "400Mi"
          requests:
            cpu: 400m
            memory: "400Mi"
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: polymetrie-hpa
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: polymetrie-app
#     namespace: default
#   minReplicas: 1
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50