apiVersion: v1
kind: Service
metadata:
  name: polymetrie-service
  namespace: default
  labels:
    app: polymetrie-app
spec:
  selector:
    app: polymetrie-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
