apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: prometheus
spec:
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchLabels:
      name: polymetrie-app-monitor
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
