apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: polymetrie-service
  namespace: default
  labels:
    app: polymetrie-app
spec:
  selector:
    matchLabels:
      app: polymetrie-app
  endpoints:
  - port: web