---
- name: Deploy Polymetrie Application
  hosts: localhost

  tasks:
    - name: Add the Bitnami Chart Repository
      kubernetes.core.helm_repository:
        name: bitnami
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Apply PostgreSQL Database
      kubernetes.core.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        values_files:
          - ../kubernetes/postgresql-values.yaml
        state: present

    - name: Apply Redis Database
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: default
        values_files:
          - ../kubernetes/redis-values.yaml
        state: present


    - name: Wait for PostgreSQL to be ready
      pause:
        seconds: 20

    - name: Apply Polymetrie Deployment
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/polymetrie-deployment.yaml

    - name: Apply Polymetrie Service
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/polymetrie-service.yaml

    - name: Apply Polymetrie Ingress
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/polymetrie-ingress.yaml