---
- name: Deploy Polymetrie Application
  hosts: localhost
  gather_facts: false
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Add Helm Chart Repository
      kubernetes.core.helm_repository:
        name: stable
        repo_url: "https://charts.bitnami.com/bitnami"

    - name: Deploy PostgreSQL Database
      kubernetes.core.helm:
        name: postgresql
        chart_ref: bitnami/postgresql
        release_namespace: default
        create_namespace: true
        values:
          postgresqlPassword: "cBxkAqQtZR"

    - name: Deploy Redis Database
      kubernetes.core.helm:
        name: redis
        chart_ref: bitnami/redis
        release_namespace: default

    - name: Wait for Redis and Postgres deployment to finish
      pause:
        seconds: 20

    - name: Apply Kubernetes YAML files
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', item) }}"
      with_items:
        - ../kubernetes/polymetrie-deployment.yaml
        - ../kubernetes/polymetrie-service.yaml
        - ../kubernetes/polymetrie-ingress.yaml
