---
- name: Deploy Prometheus Stack
  hosts: localhost

  tasks:
    - name: Add Prometheus Community Chart Repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Apply Prometheus Stack
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: prometheus
        create_namespace: true
        values_files:
          - ../kubernetes/prometheus-values.yaml

    - name: Apply Prometheus Ingress
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/prometheus-ingress.yaml
        namespace: prometheus

    - name: Apply Polymetrie Service Monitor
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/polymetrie-service-monitor.yaml
        namespace: prometheus

    - name: Apply Prometheus Service Account
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/prometheus-service-account.yaml
        namespace: prometheus
    - name: Apply Prometheus Config
      kubernetes.core.k8s:
        state: present
        src: ../kubernetes/prometheus-config.yaml
        namespace: prometheus
